services:
#    pp_mentor.example:
#        class: PPMentorBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  pp_mentor.twig_extension:
      class: PPMentorBundle\Twig\BoolExtension
      public: false
      tags:
          - { name: twig.extension }

  pp_mentor.listener:
      class: PPMentorBundle\Listener\RegisterPadawanNotifyOnSlackListener
      arguments:
          - '@circle.restclient'
          - '%slack_hook_url%'
      tags:
          - { name: kernel.event_listener, event: pp.padawan_regstered, method: notify }

