<?php

namespace PPMentorBundle\Repository;

/**
 * PadavanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PadavanRepository extends \Doctrine\ORM\EntityRepository
{
}
