<?php

namespace PPMentorBundle\Repository;

/**
 * PadawanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PadawanRepository extends \Doctrine\ORM\EntityRepository
{
}
